[CFM_126] chore: Setup Unit Testing
CollectiveFocus/CFM_Frontend pull request #127
Opened 2023-03-16 02:31 UTC by seanred360

This sets up unit testing with Jest and React Testing Library.

2023-03-16 04:21 UTC, jaronaearle requested changes
I would suggest adding a simple test or two to some of the components to actually verify that this is config is set up properly.

2023-03-16 13:05 UTC, seanred360 commented
> I would suggest adding a simple test or two to some of the components to actually verify that this is config is set up properly.

Thanks for taking a look! I actually have some tests I just was not sure if I should include them or not.

2023-03-16 23:22 UTC, seanred360 commented
> I would suggest adding a simple test or two to some of the components to actually verify that this is config is set up properly.

I added a few very simple tests. The one that tests format.js fails because the function doesn't work. I have a fix in another PR that will pass the test. Currently I am trying to figure out how to test components. Most of the components we use are abstracted behind MUI and have state and other dependencies that are hard to insolate.

2023-03-16 23:36 UTC, jaronaearle commented
> > I would suggest adding a simple test or two to some of the components to actually verify that this is config is set up properly.
> 
> I added a few very simple tests. The one that tests format.js fails because the function doesn't work. I have a fix in another PR that will pass the test. Currently I am trying to figure out how to test components. Most of the components we use are abstracted behind MUI and have state and other dependencies that are hard to insolate.

If you'd like some help getting started with testing components let me know. I should have some time tomorrow or over the weekend and we could pair on that if you'd like.

2023-03-17 00:13 UTC, seanred360 commented
> > > I would suggest adding a simple test or two to some of the components to actually verify that this is config is set up properly.
> > 
> > 
> > I added a few very simple tests. The one that tests format.js fails because the function doesn't work. I have a fix in another PR that will pass the test. Currently I am trying to figure out how to test components. Most of the components we use are abstracted behind MUI and have state and other dependencies that are hard to insolate.
> 
> If you'd like some help getting started with testing components let me know. I should have some time tomorrow or over the weekend and we could pair on that if you'd like.

I would love that! I am free tomorrow between 9 - 6

2023-03-18 04:48 UTC, jaronaearle commented on package-lock.json
This lock file should be deleted as we should only be using one package manager. After removing this file, run `yarn install` and add/commit the yarn.lock file.

2023-03-18 13:44 UTC, seanred360 commented on package-lock.json
I fixed the issue thanks!

2023-03-29 05:17 UTC, jaronaearle submitted a review, later dismissed
Solid work, lgtm 🚀

2023-05-06 13:00 UTC, bernardm approved these changes

2023-05-06 16:41 UTC, bernardm approved these changes

2023-05-06 16:49 UTC, merged