[CFM_219] Setup github actions in frontend
CollectiveFocus/CFM_Frontend pull request #131
Opened 2023-03-27 22:45 UTC by seanred360

This workflow: 

installs node deps and caches node_modules
- runs yarn build
- runs yarn test
- runs yarn lint

2023-03-27 22:49 UTC, seanred360 commented
The tests fail because Jest has not been merged in CFM_126

2023-03-28 02:01 UTC, jaronaearle requested changes
Since the success of this workflow is dependent on CFM_126, I'd suggest merging CFM_126 into this branch in order for it to be complete.

2023-03-28 02:01 UTC, doomjar commented on .github/workflows/main.yml
> +          node-version: "19"
Should this line be replaced with `node-version-file: ".nvmrc"`?

2023-03-28 02:01 UTC, doomjar commented on .nvmrc
> +v19.8.1
We probably don't need to include the minor and patch versions, just the major version should do.

2023-03-28 02:01 UTC, doomjar commented on .github/workflows/main.yml
> +          yarn lint
Please add a single newline to the end of this and the .nvmrc files.

2023-03-28 19:43 UTC, closed without merging